"""empty message

Revision ID: 7c1d7edb6520
Revises: 4ec4f3a335a3
Create Date: 2023-09-18 14:56:53.596367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1d7edb6520'
down_revision = '4ec4f3a335a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rewards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reward', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rewards_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rewards_pkey')
    )
    op.drop_table('reward')
    # ### end Alembic commands ###
