"""empty message

Revision ID: c85adb8a6933
Revises: 7c1d7edb6520
Create Date: 2023-09-19 14:45:17.002208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85adb8a6933'
down_revision = '7c1d7edb6520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_column('reward')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
